server:
  port: 8001

spring:
  application:
    name: ai-agent
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${spring.ai.dashscope.api-key}
      chat:
        options:
          model: qwen-plus


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wht.ai2025.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

search-api:
  api-key: ${search-api.api-key}